version: '2'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user123
      MONGO_INITDB_ROOT_PASSWORD: user123
    volumes:
      - 'mongodb_data:/data/db'

  # mongo-express:
  #   image: mongo-express
  #   ports:
  #     - 9000:9000
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: user123
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: user123
  #     ME_CONFIG_MONGODB_URL: mongodb://user123:user123@mongo:27017/

volumes:
  mongodb_data:
    driver: local
